name: "Setup Fastlane"
description: "Installs Ruby and Fastlane"
inputs:
  ruby-version:
    description: "Ruby version to install"
    required: false
    default: "3.2.2"
  bundler-version:
    description: "Bundler version to install"
    required: false
    default: "2.5.6"
  fastlane-dir:
    description: "Fastlane working directory"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    # Setting up ruby
    - name: Set up Ruby
      id: set_up_ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby-version }}
        bundler-cache: false
        working-directory: ${{ inputs.fastlane-dir }}

    # Installing bundler to use fastlane on the machine
    - name: Install fastlane
      id: install-fastlane
      working-directory: ${{ inputs.fastlane-dir }}
      shell: bash
      run: |
        gem install bundler:${{ inputs.bundler-version }}
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
