name: "create tag"
runs:
  using: "composite"
  steps:
    - name: Setup Dart
      uses: dart-lang/setup-dart@v1

    - name: Get package version
      id: get_version
      shell: bash
      run: echo "::set-output name=version::$(awk '/^version:/ {print $2}' pubspec.yaml)"
      
    - name: check tag
      uses: mukunku/tag-exists-action@v1.2.0
      id: checkTag
      with: 
        tag: ${{ steps.get_version.outputs.version }}

    - name: Create Git tag
      shell: bash
      if: ${{ steps.checkTag.outputs.exists == 'false' }}
      run: |
        git tag v${{ steps.get_version.outputs.version }}
        git push origin v${{ steps.get_version.outputs.version }}
