# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: AHA PROD Workflow

# Controls when the workflow will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Android-App-Release-Prod:
    environment: aha-prod
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: android
    steps:
      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Setup Fastlane
        uses: ./.github/actions/setup_fastlane
        with:
          fastlane-dir: android
      - name: Promote to Playstore
        run: bundle exec fastlane promote_beta_to_production_aha
        env:
          PLAYSTORE_JSON_KEY_DATA: ${{ secrets.PLAYSTORE_JSON_KEY_DATA }}

  iOS-App-Release-Prod:
    environment: aha-prod
    runs-on: macos-15
    defaults:
      run:
        shell: bash
        working-directory: ios
    steps:
      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Setup Fastlane
        uses: ./.github/actions/setup_fastlane
        with:
          fastlane-dir: ios
          
      - name: Promote to Appstore
        run: bundle exec fastlane submit_beta_to_app_store_aha
        env:
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets. APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_B64: ${{ secrets.APP_STORE_CONNECT_API_KEY_B64 }}
          IOS_DEMO_USER: ${{ secrets.IOS_DEMO_USER }}
          IOS_DEMO_PASSWORD: ${{ secrets.IOS_DEMO_PASSWORD }}

