name: tesing Workflow
on:
  workflow_dispatch:
  push:
    branches: feature/aha_workflow
      

jobs: 
  testing:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout Code
       uses: actions/checkout@v2.3.4
       with:
          fetch-depth: 0
     - name: New Release Publish
       id: new_publish
       uses: release-drafter/release-drafter@v5
       with:
         publish : true
       env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
